### ISSUE TITLE
viz wrapper breaks compilation with Ascent and Catalyst in-situ wrappers

### ISSUE THREAD

**Issue by jfavre** [sphexa-org/sphexa#153]
In file included from /users/jfavre/Projects/SPH-EXA/src/sedov/sedov.cpp:19:
/users/jfavre/Projects/SPH-EXA/src/insitu_viz.h: In function 'void viz::init_ascent(DataType&, long int)':
/users/jfavre/Projects/SPH-EXA/src/insitu_viz.h:29:34: error: 'domain' was not declared in this scope
   29 |     AscentAdaptor::Initialize(d, domain.startIndex());
      |                                  ^~~~~~
/users/jfavre/Projects/SPH-EXA/src/insitu_viz.h: In function 'void viz::execute(DataType&, long int, long int)':
/users/jfavre/Projects/SPH-EXA/src/insitu_viz.h:41:31: error: 'domain' was not declared in this scope
   41 |     AscentAdaptor::Execute(d, domain.startIndex(), domain.endIndex());

In file included from /users/jfavre/Projects/SPH-EXA/src/sedov/sedov.cpp:19:
/users/jfavre/Projects/SPH-EXA/src/insitu_viz.h: In function 'void viz::execute(DataType&, long int, long int)':
/users/jfavre/Projects/SPH-EXA/src/insitu_viz.h:38:33: error: 'domain' was not declared in this scope
   38 |     CatalystAdaptor::Execute(d, domain.startIndex(), domain.endIndex());

**Comment by sekelle** [comment]
https://github.com/unibas-dmi-hpc/SPH-EXA/pull/154

Addressed here

**Comment by sekelle** [comment]
Unfortunately, we don't have any test cases yet for either Catalyst or Ascent to prevent missing silly mistakes like this.
