### ISSUE TITLE
cannot compile sphexa with the in-situ Catalyst library on eiger

### ISSUE THREAD

**Issue by jfavre** [sphexa-org/sphexa#248]
prgenv:
  module load cpeCray CMake cray-hdf5-parallel ParaView
 cd <top directory path-to-your SPH-EXA clone>
  mkdir buildCatalystEiger
  cd buildCatalystEiger
  cmake \
    -DCMAKE_CXX_COMPILER=CC \
    -DINSITU=Catalyst \
    -DBUILD_ANALYTICAL:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DSPH_EXA_WITH_H5PART:BOOL=OFF \
    ..
  make sphexa

In file included from /users/jfavre/Projects/SPH-EXA/domain/include/cstone/domain/domain.hpp:41:
/users/jfavre/Projects/SPH-EXA/domain/include/cstone/focus/octree_focus_mpi.hpp:264:9: error: no member named 'exclusive_scan' in namespace 'std'; did you mean 'stl::exclusive_scan'?
        std::exclusive_scan(leafCounts_.begin() + firstIdx, leafCounts_.begin() + lastIdx + 1,
        ^~~~~~~~~~~~~~~~~~~
        stl::exclusive_scan
/

**Comment by sekelle** [comment]
This is due to the system GCC being too old (8.1.0)
```
uan03:~$ echo $GCC_X86_64 
/opt/cray/pe/gcc/8.1.0/snos
```
This can be fixed by changing to a newer version:
```
export GCC_X86_64=/opt/cray/pe/gcc/9.3.0/snos
```

**Comment by jfavre** [comment]
I don't use gcc for ParaView. See the README.insitu instructions:

module load cpeCray CMake cray-hdf5-parallel ParaView

**Comment by sekelle** [comment]
cpeCray or cray-clang depend on system GCC headers, therefore the fix above is valid also when not using GCC.
